name: Run ETHOS.PeNALPS Tests

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:
    branches: main


jobs:
  run_test_on_micromamba:
      name: Run test on micromamba image
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: .
      steps:
        - name: Check out the repository to the runner
          uses: actions/checkout@v4  
        - name: echo current working directory
          shell: bash
          run: |
            ls
            cd ..
            ls
        - name: list
          run:  |
              ls ${{ github.workspace }}
        - uses: mamba-org/setup-micromamba@v1
          with:
            micromamba-version: '1.5.1-1'
            environment-file: environment.yml
            init-shell: bash
            cache-environment: true
            post-cleanup: 'all'
        - name: activate new environment
          run: micromamba activate ethos_penalps
        - name: install ETHOS.PeNALPS itself with pip
          run: pip install -e .
        - name: Start tests
          run: pytest
        - name: Echo that workflow terminated
          run: echo "Unit tests are terminated"
